services:
  db:
    image: postgres:15-alpine
    container_name: optisaas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: optisaas
    ports:
      - "5435:5432"
    volumes:
      - pgdata_fresh:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: optisaas-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/optisaas?schema=public"
      MINIO_ENDPOINT: "host.docker.internal"
      MINIO_PORT: "9002"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "optisaas"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
      WATCHPACK_POLLING: "true"
      WEBPACK_WATCH_OPTIONS_POLL: "500"
      FAST_REFRESH: "true"
      NG_CLI_ANALYTICS: "false"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: optisaas-frontend
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
      WATCHPACK_POLLING: "true"
      WEBPACK_WATCH_OPTIONS_POLL: "1000"
      NG_CLI_ANALYTICS: "false"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: optisaas-prisma-studio
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db:5432/optisaas?schema=public"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma studio --browser none"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata_fresh:
