
server {
    listen 4201;
    server_name 151.80.146.74; # Ou votre domaine si vous en avez un

    root /home/ubuntu/projects/optisaas-demo/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers l'API Backend Demo (Port 3003)
    location /api {
        proxy_pass http://localhost:3003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
